### ISSUE TITLE
Unknown country code for phone number +8345678345

### ISSUE THREAD

**Issue by rajkamal-kiwi** [catamphetamine/react-phone-number-input#427]
Uncaught Error: Unknown country: undefined
    at getCountryCallingCode (metadata.js:508:1)
    at getInternationalPhoneNumberPrefix (getInternationalPhoneNumberPrefix.js:10:1)
    at getPhoneInputWithCountryStateUpdateFromNewProps (getPhoneInputWithCountryStateUpdateFromNewProps.js:166:1)
    at getDerivedStateFromProps (PhoneInputWithCountry.js:398:1)
    at applyDerivedStateFromProps (react-dom.development.js:12594:1)
    at updateClassInstance (react-dom.development.js:13198:1)
    at updateClassComponent (react-dom.development.js:17098:1)
    at beginWork (react-dom.development.js:18611:1)
    
   The user cannot enter this phone number because there's validation on frontend but if database is updated with number then the component breaks.

**Comment by fender2** [comment]
Try adding `defaultCountry: string?` property and see if this fixes the problem.
